### ISSUE TITLE
Mimic Gitlab Branch Names?

### ISSUE THREAD

**Issue by Puddinglord** [robvanderleek/create-issue-branch#125]
First off, I love this action! 

I come from Gitlab where you can create a branch from an issue and the default naming convention for Gitlab is `{issue number}-{issue title/name}`.

The option `full` does almost everything but it has `issue` at the front and then the `issue number`. Would it be possible to make it so the `issue number` comes first and to drop the word `issue`?

I can see that customization was done in issue #17. I would like that extended if possible.

**Comment by robvanderleek** [comment]
Hi @Puddinglord 

Thanks for the feedback 😄 

The current configuration options for `branchName` are `{tiny, short, full}`. In issue #97 there's a discussion to make the branch name fully configurable, see https://github.com/robvanderleek/create-issue-branch/issues/97#issuecomment-592989690 By implementing that functionality users can have GitLab-like branch names by specifying:
```yaml
branchName: '${issue.number}-${issue.title}`
```
However, I suspect more developers that come from GitLab have the same request so it might be safer to just add a `gitlab` option for `branchName`.

What do you think?

**Comment by Puddinglord** [comment]
I think that would be a perfect solution. Naming the option `gitlab` would also be very intuitive.

**Comment by robvanderleek** [comment]
Eventually I implemented the custom branch name feature since I noticed the default naming convention of GitLab differs on other points too (i.e.: branch names are all lowercase and spaces are replaced with '-' characters). Adding a `gitlab` option would then be confusing.

To have your branches contain just the issue number and title add this to your `.github/issue-branch.yml`:

```yaml
branchName: '${issue.number}-${issue.title}`
```

(To have all your repos follow this convention, create the yaml in a repo called `.github`.)

Let me know if this works for you 😄 
Stay safe

**Comment by Puddinglord** [comment]
Exactly what I needed! Thank you very much 🙌
