### ISSUE TITLE
Possible Improvements

### ISSUE THREAD

**Issue by Puddinglord** [robvanderleek/create-issue-branch#142]
Back again!

I am loving the custom branch naming and again want to thank you for implementing that 👏 

I noticed that on a Github Project board there is "automation" but I feel like it's lacking. I was wondering if `create-issue-branch` could support the following features?

1. Automatically moving the issue to the "In Progress" column when a branch is created. I use chatops mode and only create the branch when I am ready to work on an issue. Right now I manually go to the board and move it to the "In Progress" column.

2. I see that you have a new feature that will auto close an issue when a matching pull request is made and it can find the issue number. Will that work with the custom naming that I have? 
`${Issue-number}-${issue-name}`. If not, would it be possible to support it?

3. Based on number two if you can already auto close using the custom naming feature would it be possible to move an issue to the "Ready For Review" column when I create a pull request for a matching issue?

If you need me to elaborate on any of these please let me know. I am really fond of this app and it helps me use Github more efficiently every day.

**Comment by robvanderleek** [comment]
Welcome back @Puddinglord 😄 

To start with 2.: Yes, the `autoCloseIssue` feature should work with that naming convention (let me know otherwise). 
There are a few [restrictions](https://github.com/robvanderleek/create-issue-branch#automatically-close-issues-after-a-pull-request-merge) on the branch name for this feature to work (because the issue number needs to be parsed from it) but your convention should work fine.

Regarding 1. and 3.:

This app currently does not have read/write access to the repo Project:

![image](https://user-images.githubusercontent.com/5324924/80277003-6c8ff900-86ec-11ea-9bb2-5860161ba8f3.png)
 
and I'm a bit hesitant to ask users for more permissions (but it is an option of course).

GitHub has some [automation features for project boards](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-project-boards) available, could that be leveraged?

Again, thanks a lot for your input.

**Comment by Puddinglord** [comment]
Awesome to hear on 2, 👏 I shall try it out. 

For 1 and 3: I use a code coverage tool called CodeCov. When signing up, you give it base access and that covers public repositories. When you want it to access private repositories it another authorization screen comes up and asks for the new permissions. Would that be possible here? Have the base permissions be the ones you have now and then be able to elevate them if people want to use more advanced features like the ones I asked about?

**Comment by robvanderleek** [comment]
I think the authorization scheme you are describing is the one used by OAuth applications. Those applications can gradually extend the permission scope when needed.

For GitHub "Apps" I must select the required permissions upfront. Changes to permissions will be applied to all future installations. Current users will be prompted to accept any changes and enable the new permissions on their installation.

Since I don't want to bother current users too much with these permission changes I'm saving up issues that require a permission change and decide later which one to implement. I've placed a section for this on the [README](https://github.com/robvanderleek/create-issue-branch#roadmap-features)

**Comment by jllodra** [comment]
For the point 1, I use this https://github.com/philschatz/project-bot, when the issue is created it appends to the TODO column, when the issue is assigned (so the branch is created by create-issue-branch), the card is moved to IN PROGRESS. Finally, when the pull request associated is merged, create-issue-branch closes the issue and deletes the branch, and project-bot moves the card to the DONE column. You could solve point 3 maybe with a similar approach.

Hope this helps you.

**Comment by robvanderleek** [comment]
Thanks for describing your setup @jllodra 😄

**Comment by TGTGamer** [comment]
+1 Would love. Currently using https://github.com/technote-space/auto-card-labeler & https://github.com/takanabe/github-actions-automate-projects to power my automation of this.
