### ISSUE TITLE
Custom settings is not working

### ISSUE THREAD

**Issue by GabrielNexT** [robvanderleek/create-issue-branch#205]
Hi Rob, your application is amazing, I am in an organization where it is being used and it works perfectly, however I created an organization and tried to use it and I am not able to configure it correctly.

I'm putting issue-branch.yml in the path: `/.github/blob/master/.github/issue-branch.yml`

Apparently the app is not reading and is using the default setting.

This is the content of issue-branch.yml
```
silent: false
branchName: tiny
autoCloseIssue: true
```

**Comment by robvanderleek** [comment]
Hi @GabrielNexT 

Thanks, nice to hear 😄 

It's not completely clear to me what your setup is, I'll explain the placement options for the YAML, maybe that helps:

1. If you want to configure the Create Issue Branch App for a single repository, just create a configuration in `.github/issue-branch.yml`
2. If your want to configure the Create Issue Branch App globally, so for all repositories, first create a *repository* called `.github` (yes, I know, this is a bit awkward). Then, inside that repository create a configuration file in `.github/issue-branch.yml`

You can create the `.github` repository in your personal GitHub account (to globally configure it for your own repositories) or an organization account.

Note that the configuration file in 1. always has priority over the one in 2.

Hope this helps, otherwise let me know.

**Comment by GabrielNexT** [comment]
Thanks for the answer!

I honestly didn't understand why the global configuration was not working, should the organization's .github repository be public or something?
I managed to use it with method 1. I was doing it correctly, but on the wrong branch.

I just didn't understand why the global configuration doesn't work. I created a private .github repository in my organization, a .github folder and added the issue-branch.yml file, but apparently it was ignored or there is a very SIMPLE error and I didn't notice.

Anyway, error resolved. The issue can be closed. Thanks for your attention and for the app!
