### ISSUE TITLE
Feature request: choose source branch

### ISSUE THREAD

**Issue by pablo-de-andres** [robvanderleek/create-issue-branch#213]
I personally find the possibility to choose the source branch quite important. I know that rules can be added based on the labels, but that also requires the source branch name (e.g. `dev`) to stay the same, since it will be hardcoded in the config file.

It would be nice to be able to do something like `/cib source-branch`.

**Comment by robvanderleek** [comment]
Hi @pablo-de-andres 

Thanks for your feedback 😄 

In another [issue](https://github.com/robvanderleek/create-issue-branch/issues/155) we've discussed this option too.
Do you want to select an arbitrary branch or another issue-branch (as discussed in #155)?
Can you tell me a bit about your use-case for this feature?

**Comment by pablo-de-andres** [comment]
My bad, I checked the opened issues for something similar, didn't consider the closed ones. 😅 

I would choose an arbitrary branch. Like you mentioned, I also very rarely branch from issue branches.

My workflow is:
- `master` contains the stable releases.
- Every time I start working on a new release, I create a _dev_ branch.
   I'm considering naming it `dev`, but for now each one is named with the release version number (e.g. `v3.2.0-dev`). 
- I branch from the _dev_ branch with the issues assigned to that new milestone/release.

**Comment by robvanderleek** [comment]
Thanks for explaining your use-case @pablo-de-andres 

A way to currently support this branching scheme would be to create a release label, say `v3.2.0`, and then configure this app to take `v3.2.0-dev` as the source branch for issues with this label. Example configuration YAML:

```yaml
branches:
  - label: v3.2.0
    name: v3.2.0-dev
```

This currently only works with labels, not milestones, but that would not be very difficult to implement.

I'm a bit hesitant to add support for arbitrary branch names in the ChatOps interface since typing `/cib v.3.2.0-dev` in the issue conversation seems error-prone to me. Also, the arguments after `/cib` can currently be configured to [override the branch name](https://github.com/robvanderleek/create-issue-branch#branch-name-as-chatops-command-argument) so I'm not sure how to support both use-cases with the ChatOps interface.

**Comment by pablo-de-andres** [comment]
Ok, thank you!

That would require to also change the configuration file for every release, though...

**Comment by robvanderleek** [comment]
Yeah, I admit that is cumbersome.

Do you mind if I add your issue to the [Features under Consideration](https://github.com/robvanderleek/create-issue-branch#features-under-consideration) list?
I'm not sure at the moment how/if the ChatOps interface should be extended.

Admittedly there is not a lot of progress on issues that end up on that list, but if more people request this feature I can come back to it.

**Comment by pablo-de-andres** [comment]
Sure, no worries.

And thanks a lot for the consideration and support! 😃
