### ISSUE TITLE
Feature request: Config parameter to stop receiving emails

### ISSUE THREAD

**Issue by raghavmalawat** [robvanderleek/create-issue-branch#260]
Is there any way, we stop getting emails for every issue-branch created and assigned. 
While I love using this project, my mailbox becomes quite messy.

**Comment by robvanderleek** [comment]
Hi @raghavmalawat 

You can configure this App [to be silent](https://github.com/robvanderleek/create-issue-branch#silent-or-chatty).
If you create a [user/organization wide configuration](https://github.com/robvanderleek/create-issue-branch#organizationuser-wide-configuration) YAML this should stop the e-mails.

Since GitHub also sends notifications for bots, it's unfortunately not possible to have this App comment on the issue after creating a branch while preventing the e-mails.

**Comment by raghavmalawat** [comment]
Oh Okay! Thanks @robvanderleek 
Configuring the App to be silent will definitely help
