### ISSUE TITLE
CIB command no longer working after adding a configuration file

### ISSUE THREAD

**Issue by MerlinCooper** [robvanderleek/create-issue-branch#307]
Might do something wrong but seems that the /CIB command is no longer working after I added a YAML file to be able to create a sub-branch based on a different branch than master. 

Here is the YAML configuration file I'm currently using [link](https://github.com/MerlinCooper/iRacingReplayDirector/blob/master/.github/issue-branch.yml)

P.S.: When I assign the issue the branch is created correctly. Do I have to add more attributes to the YAML file than just those I want to overwrite?

**Comment by robvanderleek** [comment]
Hi @MerlinCooper 

The default behaviour is that a branch is created when an issue is assigned (at least, that should be the default, let me know otherwise).
You can also use the App in "ChatOps" mode by adding `mode: chatops` to your configuration YAML (see also the [Readme](mechelen.degroot@hotmail.com))

Can you see if this resolves your problem?
KR, Rob
