### ISSUE TITLE
Extra Long Names Error

### ISSUE THREAD

**Issue by sirwolfgang** [robvanderleek/create-issue-branch#344]
With the full title auto-creation it's possible for branches to be created that are too long to upload. There is a 255 size limit on the refs.

**Comment by robvanderleek** [comment]
Hi @sirwolfgang 
Thanks for reporting. I've seen this issue [before](https://github.com/robvanderleek/create-issue-branch/issues/303) and branch names are since then truncated to a safe length. But apparently there are still issues with long branch names.
Can you share your config and (if possible) the branch name?

**Comment by sirwolfgang** [comment]
This was our config
```
openDraftPR: true
autoCloseIssue: true
branchName: 'issue-${issue.number}-${issue.title,}'
```
That was then combining with a HoneyBadger generated ticket for `issue-1285-nomethoderror_nomethoderror_undefined_method_apply_filters_for_activerecord_associationrelation_transaction_id_318343bf-e017-4a97-85ec-fbe1ba56174b_date_2021-02-22_amount_cents_633_description_uber_072515_sf_pool_created_at_2021-03-04_11_0` [All Demo Data]
Interesting the branch and PR was created, but it failed when I tried to push a new commit to it.

**Comment by robvanderleek** [comment]
Thanks for details.
I could reproduce the error, it gave a very helpful error message from GitHub and allowed me to [refine](https://stackoverflow.com/a/66514473/4232558) the current limit.
Thanks for reporting!
