### ISSUE TITLE
When the bot creates a pull request, it'll be listed as author on the commit. Can that change?

### ISSUE THREAD

**Issue by nhoening** [robvanderleek/create-issue-branch#360]
I love the `openDraftPR` feature ― thanks :)

However, I would prefer that the Github user who is assigned to the ticket (which originally led to the new branch and PR) would be the one listed as the author of the merge commit, and not `create-issue-branch [bot]`.

**Comment by robvanderleek** [comment]
Hi @nhoening 😄 

The behaviour you describe has been mentioned by others (for example see [this discussion](https://github.com/robvanderleek/create-issue-branch/issues/80#issuecomment-760767236) but unfortunately I haven't found a solution.

Just for my understanding: are you using the CIB App or GitHub Action?
For both options I don't think it's possible to let the App/Action "impersonate" the user that activated it.

If you know of a way to do this (or know of any Apps/Actions that do this correctly) let me know!

**Comment by nhoening** [comment]
Thanks for replying. I'm using the app I believe.

**Comment by erlete** [comment]
Hey there, sorry for being so late. Hope this is helpful anyway.

I've found out that by using your PAT (Personal Access Token) instead of the GITHUB_TOKEN, you can perform workflow operations assigned to your user. If you are working with a team, you could always set up multiple secrets with PATs for each team member, labeled, of course and then use conditional statements depending on the issue assignee to use the correct token for workflow operations.

This is a questionable procedure, given that every user would have to provide with a PAT (which some users might not like to do) and since GitHub disencourages this procedure for potential security risks. However, with brand-new fine-grained tokens this should not pose a big risk.

**Comment by robvanderleek** [comment]
Hi @erlete 👋 

The issue is still open so never too late for a proposed solution 😉 

Fine-grained access tokens would indeed be a way for the GH Action to impersonate users. 
I'm not sure if Create Issue Branch is the right place to implement this functionality. Perhaps it's possible to create a separate GH Action for this? Such an action would output a token for the current user that downstream actions (such as Create Issue Branch) can consume.
I haven't searched if such an action already exists but I guess other GH actions run into the same problem and would also benefit from it.

**Comment by Jimimaku** [comment]
> Ich liebe das Feature ― danke :)`openDraftPR`
> 
> Ich würde es jedoch vorziehen, dass der Github-Benutzer, der dem Ticket zugewiesen ist (was ursprünglich zum neuen Zweig und PR führte), derjenige ist, der als Autor des Merge-Commits aufgeführt ist und nicht.`create-issue-branch [bot]`
