### ISSUE TITLE
Link pull request when closing an issue

### ISSUE THREAD

**Issue by maxsoe** [robvanderleek/create-issue-branch#460]
I'm not sure if this is the place to make feature requests.

Does anyone know how to do this?

Right now, an issues closes when a pull request is merged (with the "autoCloseIssue: true" option).

Is there a way to link the pull request into the issue in the "linked pull requests" section?

**Comment by robvanderleek** [comment]
Hi @maxsoe

This is the right place for feature requests 😄 

Your request has been discussed before and unfortunately that issue is still open: #363 
In a nutshell: linking of Issues and PRs is not (yet?) available in the GitHub API. The only way to link Issues and PRs is through comments and description fields. I use that option when creating a PR from an Issue but when a PR is merged the only way to link it to an Issue would be to first append a comment and then close the issue. I haven't implemented that logic since I find it a very awkward workflow.

Can you please post any follow-up comments in #363 ? I'm very interested to hear what would work for your use-case.

Thanks for the feedback.
