### ISSUE TITLE
copyIssueProjectToPR + copyIssueMilestoneToPR

### ISSUE THREAD

**Issue by leovigna** [robvanderleek/create-issue-branch#505]
Would it be possible to also copy the issue's Project & Milestone to the PR? Or do you recommend using another Github Action alongside create-issue-branch?

**Comment by robvanderleek** [comment]
Hi @leovigna 

It was indeed related to the Node version (12) that GH makes available for Actions.
I've changed the Action runtime to a [small Node 14 Docker image](https://github.com/robvanderleek/create-issue-branch/blob/5546eb9d7215c1daff81ceebf06f7a589aa4a61d/Dockerfile).

Thanks for the help so far, unfortunately it took me more time than expected.
Can you please try again with the staging version of the Action? I was able to successfully open [a PR](https://github.com/facio-ergo-sum/create-issue-branch-test-repo-action/pull/3) with projects and a milestone attached myself.

**Comment by leovigna** [comment]
Test succeeded! Works great with the automated kanban template! I think we can close this issue but up to you.

**Comment by robvanderleek** [comment]
Hi @leovigna 

I've merged the PR into `main` 🚀 

Since the [copy Projects flag](https://github.com/robvanderleek/create-issue-branch#copy-attributes-from-issue) requires Project permissions, it's currently only available in the Action, so not in the App (I don't want to request extended permissions to all users of the App just for this feature). Let me know if  this works for your use-case (you can now change the Action branch back from `staging` to `main`).

Thanks so much for all the support 😄 

Best regards,
Rob
