### ISSUE TITLE
copyIssueProjectsToPR for organization project

### ISSUE THREAD

**Issue by flamisz** [robvanderleek/create-issue-branch#531]
Hi,

I'd like to use your GitHub action in my organization. We are using organization-based projects and on my test runs the `copyIssueProjectsToPR: true` did not work with these kinds of projects (but worked with repo projects). 

Is this not supported yet or did I miss something?

Thanks

**Comment by robvanderleek** [comment]
Hi @flamisz 

Sorry to hear the action does not work as expected.

For completeness: due to a GitHub permissions issue the [copyIssueMilestoneToPR](https://github.com/robvanderleek/create-issue-branch#copy-attributes-from-issue) only works in GitHub Actions, not in the GitHub App. However, you indicate you're using the action.

Can you detail a bit more what you exactly mean with organization-based projects and repo projects? Can you perhaps link to a public repo where the action does not work as expected?

KR, Rob

**Comment by flamisz** [comment]
Hi @robvanderleek,

thanks for the quick response.

Here are the issues in my test repo:
https://github.com/flamisz/f1races/issues

One has a project that is inside the same repository: 
https://github.com/flamisz/f1races/projects/2

In this case, the PR got the same project so it's on the board.

The other issue has this project:
https://github.com/users/flamisz/projects/3

which is for my user. My account is not an organization, but it's happening with org users as well.
This project is not copied to the PR.

I quickly checked your code here:

https://github.com/robvanderleek/create-issue-branch/blob/2af50fcbc49485963e065de80ff8a56fba475fd7/src/github.js#L349-L363

Maybe because this query actually includes the repository? I'm not sure if there is another way. If you have a quick idea/solution that would be great, but if don't maybe I can look into it on the weekend.

Thanks anyway

**Comment by robvanderleek** [comment]
Hi @flamisz 

Thanks a lot for the clear description and setup work!

I've checked the GraphQL query and mutation manually (using the GitHub GraphQL explorer) and that worked for both repo projects and user/org projects.

The problem seems to be the permissions of the GITHUB_TOKEN that Action workflows get. According to the [documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) "the token's permissions are limited to the repository that contains your workflow.". So no permission to access project boards outside the repo.

You could try to use a Personal Access Token in [your Actions workflow file](https://github.com/flamisz/f1races/blob/bf293a721e9cb77b41801b9c2affd6ee6ef2a330/.github/workflows/create-pr-from-issue.yml#L16) but I don't know if that's a sustainable solution for your situation.

Let me know if you have any other insights.

Best, Rob

**Comment by flamisz** [comment]
Thanks, you're right. 

I tested with a personal access token and it worked.
