### ISSUE TITLE
How about a new release?

### ISSUE THREAD

**Issue by waja** [robvanderleek/create-issue-branch#574]
Hi there,

the last release was on 25 Jan 2021. Might it be a good idea for a new stable release?

With kind regards, Jan.

**Comment by robvanderleek** [comment]
Hi @waja 

Since the publication of a new Action release to the GH Marketplace [can not be automated](https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action), I advice users of the Action [to use the `@main` branch](https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action).
The `main` branch should always be stable (the App runs from `main`).

Of course I can do another manual release? Or please let me know your suggestion to improve the release management.

Kind regards,
Rob
