### ISSUE TITLE
Suggestion for a feature to open PRs without creating a branch

### ISSUE THREAD

**Issue by uyeonyx** [robvanderleek/create-issue-branch#748]
Hi @robvanderleek,

I know from the last bug issue that you don't mind receiving enhancement feedback, so this time I'm going to make a simple enhancement suggestion.

Currently, the possible scenario is as follows
Create issue -> label and assign -> create branch -> create pull request for created branch and target branch.

This is great for most situations, but consider the following scenario

Create issue -> Label and assign -> Create pull requests for two specified branches

In other words, can you use it to merge two specific branches (as set in the YAML) at the time the issue is opened without creating any branches?

For example 
```yaml
- label: 'release'
    name: develop
    prTarget: release
    noBranch: true
```

This takes the form of specifying `noBranch` to only open the PR without creating a separate branch, so that we can simply merge it into the develop branch -> release branch. 

This would be useful for when we just want to merge our development into a release, assuming you follow a typical git flow.

I know this can be done by just opening a pull request, but it would be nice to be able to do it in an issue-driven workflow.

<img width="669" alt="image" src="https://github.com/robvanderleek/create-issue-branch/assets/65580604/24b2c512-3e8a-44a4-bfc6-b323f3d093d8">

That is, it will be especially useful at the red boxed point in this image.

Alternatively, if this is possible in the current specification, please let me know how to do it (besides writing a separate action workflow).

**Comment by robvanderleek** [comment]
Hi @uyeonyx 

Wow, I'm really impressed with the quality of this feature request.

Create Issue Branch already has a [`skip`](https://github.com/robvanderleek/create-issue-branch/tree/issue-748-Suggestion_for_a_feature_to_open_PRs_without_creating_a_branch#skip-runs-for-issues-based-on-issue-label) flag, so I've named the flag for this feature [`skipBranch`](https://github.com/robvanderleek/create-issue-branch/tree/issue-748-Suggestion_for_a_feature_to_open_PRs_without_creating_a_branch#skip-branch-creation-based-on-issue-label).

I've deployed the new functionality to the staging environment. If you want to test it yourself, you can [install the staging app here](https://github.com/apps/create-issue-branch-staging).
[This issue](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-staging-app/issues/33) shows how the functionality works.
While writing this response I realize the empty commit message is probably not needed for existing branches (it is needed to open (draft) PRs for new branches since they have no existing commits). I'll look into that before merging to main.

In case you have any feedback, please let me know 🙂 

KR, Rob

**Comment by uyeonyx** [comment]
Hi @robvanderleek 
Sorry for the late feedback.

I installed the staging app in my test repository and tried out a few scenarios.

It worked fine and hit the spot.
I didn't have any bugs or other issues.

I mention my actual use case, in case you are curious.
<details><summary>Details</summary>
<p>
I wanted to proceed with an issue-centric CICD strategy as follows

1. create a release issue with the semantic version strategy in the title.
Example) release private beta #patch

2. give it a release label and assignment, which creates a develop -> release PR without creating a separate branch.

3. when it is reviewed and merged, the title of the issue (the title of the PR) is included in the commit message.

4. a separate workflow detects the commit message when a push is made to the release branch, automatically increments the release version and proceeds with automatic build and release uploads.

</p>
</details> 

I had envisioned a scenario like this earlier, but the issue -> PR creation didn't work the way I wanted it to and that was a big tickler for me.

Anyway, this small change has provided me with great convenience.
It would be great to see this released.
Thank you very much. 👍

**Comment by robvanderleek** [comment]
Hi @uyeonyx 

I've just merged in the PR, is it now available in the regular App.

Since you're mentioning semantic versioning: Create Issue Branch supports updating PR titles with issue labels (Conventional Pull Request titles). You might want to check this feature (or maybe it's not relevant for your development process).

KR, Rob
