### ISSUE TITLE
gitSafeReplacementChar: '-' does interesting things

### ISSUE THREAD

**Issue by JBruns15** [robvanderleek/create-issue-branch#819]
When i have a Ticket named:

Please fix - nasty bug

And i replace every Space with - 

It would look like:
please-fix---nasty-bug

What can i do about that?

Sorry when it is not an Issue.

Thanks

**Comment by robvanderleek** [comment]
Hi @JBruns15 

As I understand you have configured `gitSafeReplacementChar: '-'` for this repository?
That will indeed create a branch named `Please-fix---nasty-bug` for an issue titled `Please fix - nasty bug`.
Is this not what you expected?
Please let me know what you expected, because what you describe is the intended behaviour.

Kind regards, Rob

**Comment by JBruns15** [comment]
Hi @robvanderleek ,

i undertand it now. Thanks. 
But is there a possibilite to use the `gitSafeReplacementChar` and avoid triple `-` ?

Thanks a lot :)

**Comment by robvanderleek** [comment]
I don't think so 🤔 
`gitSafeReplacementChar` replaces all characters that are not allowed in Git branch names, so `<space>-<space>` becomes `---` (or `_-_` with the default setting).
I would not know a way that prevents this behaviour, unless it's a very specialized feature to replace `---` with `-` but that looks like a feature only a very limited number of users would use.
